# Generated by Django 2.2.5 on 2019-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_info_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orgnisation',
            field=models.CharField(default='Unknown', max_length=264),
        ),
        migrations.AddField(
            model_name='person',
            name='skill',
            field=models.CharField(default='Unknown', max_length=264),
        ),
        migrations.AddField(
            model_name='person',
            name='skill_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default='Unknown', max_length=264),
        ),
    ]
